### ISSUE TITLE
CMake is throwing error during build setup during RFmx gRPC Build

### ISSUE THREAD

**Issue by RahulBenaka** [ni/grpc-device#1125]
I have been trying to run this command locally `cmake .. -A x64` to get the proto files for RFmx gRPC Server APIs and I'm getting the below error

  **The source directory**

    C:/gRPC/grpc-device/third_party/grpc-sideband

  **does not contain a CMakeLists.txt file.**
  (Go to End of this section to see the command window output)
  
  I was trying to resolve the issue and I tried removing entries of "grpc-sideband" in CMakeLists.txt and that helped me resolve it temporarily (using that as a workaround to generate the proto files). The entries for "grpc-sideband" was added in this PR : #1113 
  
  Please let me know if there's any new steps I need to include to fix this issue. 

**Command Window Output:**

`PS C:\gRPC\grpc-device\build> cmake .. -A x64
-- Selecting Windows SDK version 10.0.22000.0 to target Windows 10.0.19044.
Setting policy CMP0091 and runtime library
CMake Warning at third_party/grpc/third_party/abseil-cpp/CMakeLists.txt:70 (message):
  A future Abseil release will default ABSL_PROPAGATE_CXX_STD to ON for CMake        
  3.8 and up.  We recommend enabling this option to ensure your project still
  builds correctly.

CMake Warning at third_party/grpc/third_party/protobuf/cmake/CMakeLists.txt:3 (message):
  Calling of cmake with source directory set to "cmake" subdirectory of   
  Protocol Buffers project is deprecated.  Top-level directory of Protocol
  Buffers project should be used instead.

-- 
-- 3.21.6.0
CMake Warning at third_party/grpc/cmake/ssl.cmake:37 (message):
  Disabling SSL assembly support because NASM could not be found
Call Stack (most recent call first):
  third_party/grpc/CMakeLists.txt:324 (include)

CMake Deprecation Warning at third_party/grpc/third_party/zlib/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

CMake Deprecation Warning at third_party/gtest/CMakeLists.txt:4 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

CMake Deprecation Warning at third_party/gtest/googlemock/CMakeLists.txt:45 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

CMake Deprecation Warning at third_party/gtest/googletest/CMakeLists.txt:56 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- Using the single-header code from C:/gRPC/grpc-device/third_party/json/single_include/
CMake Error at CMakeLists.txt:50 (add_subdirectory):
  **The source directory

    C:/gRPC/grpc-device/third_party/grpc-sideband

  does not contain a CMakeLists.txt file.**

-- Configuring incomplete, errors occurred!
See also "C:/gRPC/grpc-device/build/CMakeFiles/CMakeOutput.log".
See also "C:/gRPC/grpc-device/build/CMakeFiles/CMakeError.log".`

[AB#2937630](https://dev.azure.com/ni/94b22d7b-ad7b-4f5e-88f0-867910f91c94/_workitems/edit/2937630)

**Comment by asumit** [comment]
Did you run git submodule update --init --recursive

**Comment by RahulBenaka** [comment]
This command helped me resolve it. Thank you.
