### ISSUE TITLE
grpc-device exports do not include NOTICE files for subprojects which are a part of built binaries.

### ISSUE THREAD

**Issue by amstewart** [ni/grpc-device#181]
Some subcomponents of grpc-device are licensed under MIT ([json](https://github.com/nlohmann/json/blob/bb90e34d22b59ad3a15e459000fbe5a693b32397/LICENSE.MIT)); others under Apache-2 ([grpc](https://github.com/grpc/grpc/blob/ed3037de3e26b3f14a14ccf35a7e071de9e0fe0e/LICENSE)). To ensure license compliance, the grpc-device repo (and any built artifacts from the repo), should include notices that built binaries might contain code or derivatives from those projects.

An easy way to do this might be to append the [LICENSE file](https://github.com/ni/grpc-device/blob/main/LICENSE) with a notice about the applicable subprojects and their licenses. Otherwise, independent NOTICE files might be appropriate. Any notice content should be included in all export archives - per issue #180.

**Comment by kreimnitz** [comment]
Added a ThirdPartyNotices.txt.  I still need to update the releases to include this and the LICENSE file, but will do that today.
