### ISSUE TITLE
Python grpc client examples require Python 3.6 or newer

### ISSUE THREAD

**Issue by SparkingSpork** [ni/grpc-device#218]
Currently, the Python examples take advantage of f-strings. That functionality was not added until Python 3.6 as per [PEP 498](https://www.python.org/dev/peps/pep-0498/). This can cause issues if the examples are run with a NI Linux Real-Time target as the client-side since those devices currently only include Python 2.7 and Python 3.5.5 (as of the creation of this issue).

**Comment by harsha-bhushan** [comment]
The examples or the gRPC-device client are not typically run on NI Linux Real-Time targets (although technically feasible). Also the support for versions of Python lower than Python 3.6 have ended as of today. Hence we would not be fixing the examples.
