### ISSUE TITLE
betterproto exception error handling does not work in some configurations

### ISSUE THREAD

**Issue by astarche** [ni/grpc-device#282]
See #280 

betterproto will raise the underlying socket error instead of a grpc exception. Our examples attempt to filter this for better error reporting, but this does not work consistently. We should apply the DAQ implementation to the other betterproto examples.

[AB#1560637](https://ni.visualstudio.com/94b22d7b-ad7b-4f5e-88f0-867910f91c94/_workitems/edit/1560637)

**Comment by harsha-bhushan** [comment]
Adding a comment to trigger a workflow to create an equivalent AzDO bug.
