### ISSUE TITLE
Output parameters that are ivi-dance-with-a-twist may be left too big after second call

### ISSUE THREAD

**Issue by gregstoll** [ni/grpc-device#359]
This is similar to the race condition we found in #247, but sort of the opposite. If the first time we call a function and ask for the parameter's size, resize the parameter, then on the second call the size of the parameter is now smaller, we don't correctly resize the output buffer to the correct size.

We do 0-init these output buffers so there won't be garbage data in them, at least.

@harsha-bhushan - this should be a pretty straightforward fix, do you want it in the next release?

**Comment by harsha-bhushan** [comment]
If we can get it in, it would be great. But I would not prioritize this bug over the getting DAQmx release published.
