### ISSUE TITLE
Create releases notes tracking tag and template

### ISSUE THREAD

**Issue by astarche** [ni/grpc-device#381]
We need a way to mark PRs for inclusion in release notes for any breaking changes or important bug fixes.

Before closing this, #379 needs to be tagged for inclusion in the release notes OR we need to revert the API breakage.

**Comment by gregstoll** [comment]
1 sounds like kind of a pain in some cases. I think I'd lean towards 3 or 4. 4 sounds optimal if there aren't too many of these breaking changes. (which hopefully there won't be!)

**Comment by astarche** [comment]
Yeah, true. I'd say "Isolate the codegen change from addition of new APIs/features" is preferred in general and a stronger preference in this case. But, we override that preference pretty frequently for pragmatism's sake. That's fine. A softer guidance could be "think about if this change should be in release notes and, if so, what can you do to make this PR a better reference link?".

**Comment by astarche** [comment]
I went ahead and added a breaking-change tag and [tagged the appropriate PRs](https://github.com/ni/grpc-device/pulls?q=is%3Apr+label%3Abreaking-change+). I'll figure out how to handle that when adding release notes.
