### ISSUE TITLE
Registering a DAQmx callback after a task has started crashes the gRPC server and prevents future connection

### ISSUE THREAD

**Issue by sjdemartini** [ni/grpc-device#404]
In testing out various things related to https://github.com/ni/grpc-device/discussions/398, I discovered this unfortunate bug. If you attempt to register a DAQmx callback after the task has already been started, the gRPC server crashes. 

I've attached two example python scripts (using betterproto, though it seemingly shouldn't matter what the client is). One script which works [daqmx_register_working.py](https://github.com/ni/grpc-device/files/7393616/daqmx_register_working.py.txt) (registering the callback happens before starting the task) and one which causes the crash described above  [daqmx_register_crash.py](https://github.com/ni/grpc-device/files/7393615/daqmx_register_crash.py.txt) (the task is started and underway when the registration is attempted). The files have txt extensions since GitHub doesn't allow for uploading .py files.

The key part / difference is the logic near the bottom. This excerpt is from the crash version:
```python
        print("Starting task")
        await raise_if_error(await daq_service.start_task(task=task))

        print("Sleeping")
        await asyncio.sleep(2)

        print("Trying to register callbacks")
        # THIS WILL FAIL AND CAUSE THE GRPC SERVER TO CRASH
        acquisition = asyncio.gather(read_data(), wait_for_done())
        await acquisition
```

When running the "crash" script, the client will eventually see:
```
Starting task
Sleeping
Trying to register callbacks
ERROR: Connection lost
...traceback...
```

And the gRPC server will no longer be running (seemingly having crashed). Further attempts to connect to the server will fail until it's restarted manually. We didn't see any logs or messaging on the gRPC server side. We're running the server executable on Windows 10. 

Perhaps registering a callback after a task has started is not expected to work, but it seems the server should return an error to the client and avoid crashing, since this takes down the full gRPC functionality and requires human intervention to restart.

Thanks in advance for any help/attention. Really appreciate the work on the NI gRPC functionality!

**Comment by astarche** [comment]
This bug is fixed in DAQmx for the next release (not sure when that is scheduled).

**Comment by sjdemartini** [comment]
Awesome, thanks astarche!
