### ISSUE TITLE
Several functions in RFmxSpecAn have "rb_w" parameters

### ISSUE THREAD

**Issue by gregstoll** [ni/grpc-device#436]
Specifically the functions are:
- `ACPCfgRBWFilter`
- `CCDFCfgRBWFilter`
- `CHPCfgRBWFilter`
- `FCntCfgRBWFilter`
- `HarmCfgFundamentalRBW`
- `HarmFetchHarmonicMeasurement`
- `HarmFetchHarmonicMeasurementArray`
- `IMCfgRBWFilter`
- `OBWCfgRBWFilter`
- `SEMCfgCarrierRBWFilter`
- `SEMCfgOffsetRBWFilter`
- `SEMCfgOffsetRBWFilterArray`
- `SpectrumCfgRBWFilter`
- `SpurCfgRangeRBWArray`
- `SpurCfgRangeRBWFilter`
- `TXPCfgRBWFilter`

All of these functions have a parameter in their metadata named `rbW` which gRPC translates to `rb_w`. We should rename this to `rbw` in the metadata (and probably check enums and attributes as well)

[AB#1751435](https://ni.visualstudio.com/94b22d7b-ad7b-4f5e-88f0-867910f91c94/_workitems/edit/1751435)

**Comment by astarche** [comment]
There's something similar with ps_d/psd
