### ISSUE TITLE
nidcpower and nifgen have incorrect data type for Import/ExportAttributeConfigurationBuffer

### ISSUE THREAD

**Issue by bkeryan** [ni/grpc-device#694]
In the MI `ImportAttributeConfigurationBuffer` and `ExportAttributeConfigurationBuffer` functions, the `configuration` parameter is an array of bytes. The bytes contain a UTF-8 JSON string, but the API documentation doesn't document this, so it's appropriate for grpc-device to treat this parameter as an array of bytes.

`nidcpower.proto` and `nifgen.proto` incorrectly represent this parameter as `repeated fixed64 configuration`.

`nidmm.proto`, `nifake.proto`, and `niscope.proto` correctly represent this parameter as `bytes configuration`.

[AB#2108035](https://dev.azure.com/ni/94b22d7b-ad7b-4f5e-88f0-867910f91c94/_workitems/edit/2108035)

**Comment by reckenro** [comment]
Both NI-DCPower and NI-FGEN .proto files updated so those arguments are now `bytes configuration`.

NI-DCPower [ImportAttributeConfigurationBufferRequest](https://github.com/ni/grpc-device/blob/main/generated/nidcpower/nidcpower.proto#L1753) and [ExportAttributeConfigurationBufferResponse](https://github.com/ni/grpc-device/blob/main/generated/nidcpower/nidcpower.proto#L1477)

NI-FGEN [ImportAttributeConfigurationBufferRequest](https://github.com/ni/grpc-device/blob/main/generated/nifgen/nifgen.proto#L1683) and [ExportAttributeConfigurationBufferResponse](https://github.com/ni/grpc-device/blob/main/generated/nifgen/nifgen.proto#L1458)
