### ISSUE TITLE
CI-built Windows releases built with MSVC compilers not in official NI supported compiler policy

### ISSUE THREAD

**Issue by ericgross2** [ni/grpc-device#759]
Per CMake build output:
-- Building for: Visual Studio 17 2022
-- The C compiler identification is MSVC 19.33.316[30](https://github.com/ni/grpc-labview/actions/runs/3201306679/jobs/5229134939#step:7:31).0
-- The CXX compiler identification is MSVC 19.33.[31](https://github.com/ni/grpc-labview/actions/runs/3201306679/jobs/5229134939#step:7:32)630.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.[33](https://github.com/ni/grpc-labview/actions/runs/3201306679/jobs/5229134939#step:7:34).31629/bin/Hostx64/x64/cl.exe

Per official NI compiler support policy (https://dev.azure.com/ni/DevCentral/_git/Policy?path=%2Fproduct_and_technology%2FOperating-System-Support.md&version=GBmain&_a=preview&anchor=22c3%2F22c4-compilers) this is not a supported compiler. As a result, NI installers don't include the proper runtime needed and automatic installation using NI tools will be missing the runtime. Clearly this seems expected (per your installation instructions), but seems non-ideal.

[AB#2177704](https://dev.azure.com/ni/94b22d7b-ad7b-4f5e-88f0-867910f91c94/_workitems/edit/2177704)

**Comment by dmondrik** [comment]
The NI installer includes VS runtimes for 2015-2022. We received permission for including this:
_2022-10: MSVC 15.0 for gRPC Device Server_

I'm going to mark the issue as closed, but we do need to make sure we don't update the MSVC version here.
