### ISSUE TITLE
CMake fails to build in many common environments were git tags are used/unused.

### ISSUE THREAD

**Issue by amstewart** [ni/grpc-device#782]
PR #757 tries to add version metadata to the Windows build of grpc-device-server by instructing cmake to parse the build version from the nearest git tag. That isn't a reliable source for that information and breaks a lot of valid build environments.

Git tags are local to the repo, and there is no such thing as a permanent or canonical tag. One user might have the full suite of tags available on the github.com/ni/grpc-device instance, or they might have none, or some subset; and all of those scenarios are perfectly valid uses of git. Further, users are expected to be able to move tags between commits; meaning that an ni/grpc-device admin might inadvertently retag a different commit, and forever change the grpc-device server build for those affected commits.

Even further, users can add new tags in their local repo, resulting the `git describe...` command in #757 returning their local tag, which might not conform to a version string. This will happen in OE builds if you try to build grpc-device within a `devtool`-generated workspace. And you can trivially reproduce it with the following.

```bash
git clone https://github.com/ni/grpc-device
cd grpc-device
git tag foobar
git submodule update --init --recursive
mkdir build
cd build
cmake ..
```

Some of these limitations were mentioned during the PR review. But their resolution was to expect users to make their local .git data conform to this repo - which isn't realistic.

All of these considerations make git tags an unreliable source for a canonical project version.

Instead, the top-level project version should live in a source-controlled file in the repo, and a policy or workflow should update its value when a new release is created.

[AB#2208585](https://dev.azure.com/ni/94b22d7b-ad7b-4f5e-88f0-867910f91c94/_workitems/edit/2208585)

**Comment by csjall** [comment]
One of the first proposed changes in #757 was hardcoding the version in CMakeList.txt. This would have required that developers update CMakeList.txt whenever the version changes.
https://github.com/ni/grpc-device/pull/757/commits/70b4226c9796b3f587f00287d24dc067c1f308e7

Looking at gRPC library we see versions in [CMakeList.txt](https://github.com/grpc/grpc/blob/master/CMakeLists.txt). gRPC has a [handwritten file](https://github.com/grpc/grpc/blob/master/build_handwritten.yaml) and a [template](https://github.com/grpc/grpc/blob/master/templates/CMakeLists.txt.template) to generate updated CMakeList when version changes.

**Comment by SparkingSpork** [comment]
@astarche, @reckenro - Any opposition to just hardcoding the version in CMake and remembering to update it? Even looking at the handwritten file and template that @csjall links from the gRPC repo, it looks like the expectation is for someone to manually update the handwritten file and run a script to make the changes, then commit that manually (such as [here](https://github.com/grpc/grpc/pull/31618/files)). 

Otherwise, @reckenro, do you have any suggestions on making the process automated? I know you did quite a bit of the release automation work previously.

**Comment by reckenro** [comment]
I'm not opposed to hardcoding the version in CMake

I think we can go ahead and hardcode it and at least update the [Release Process Wiki page](https://github.com/ni/grpc-device/wiki/Release-Process) with the process for updating it manually.

I think after it's updated to be hardcoded manually and the Wiki is updated to provide instructions we could circle back to look into a GitHub action to run post-release to update the version instead. But I'd treat that as a separate tech debt to look into and can rely on manually creating that update/PR for now.
