### ISSUE TITLE
Error: IVI: Invalid value for parameter or property.  for attribute NIRFSG_ATTRIBUTE_DIRECT_DOWNLOAD on PXI5670

### ISSUE THREAD

**Issue by RT-Tap** [ni/grpc-device#794]
Hi I have been trying to write a waveform to our RFSG (model PXI5670) in the documentation it states 
`For the PXI-5670, direct download is always disabled. For all other devices, direct download is always enabled.` 
and therefore I need to explicitly set that attribute to enable.  However I have tried and I get the following error:
```
errorcode:-1074135024
Exception: Error: IVI: Invalid value for parameter or property.
``` 
I am using python and am able to set other attributes using this method however this one is giving me issues.  Following is the part of my code which should change the attribute and is based off of the `getting-started-single-tone-generation` example from this repository.
```
    raise_if_error( 
        client.SetAttributeViInt32(
            nirfsg_types.SetAttributeViInt32Request(
                vi = vi,
                channel_name="",
                attribute_id=nirfsg_types.NIRFSG_ATTRIBUTE_DIRECT_DOWNLOAD,,
                value=nirfsg_types.NIRFSG_INT32_ENABLE_VALUES_ENABLE
            )
        )
    )
```

I have also tried the labwindows/CVI example `WaveformFromTextFile` which is from `C:/Users/Public/Public Documents/National Instruments/CVI/samples/niRFSG/ArbitraryWaveforms/WaveformFromTextFile` which sets the attribute using 
```
   checkWarn(
      niRFSG_SetAttributeViInt32 (vi, VI_NULL, NIRFSG_ATTR_DIRECT_DOWNLOAD, directDownload));
```
However I get the same error/issue: 
```
IVI: Invalid value for parameter property

Property: NIRFSG_ATTR_DIRECT_DOWNLOAD
Valid Values: NIRFSG_VAL_DISBALE
```
I have also attached a screenshot of the labwindows/CVI example/error.

![rfsgerror](https://user-images.githubusercontent.com/71105781/202761885-90f664d0-a688-4bc9-b72f-b6873b40d555.jpg)

Thank you for your help.

[AB#2225400](https://dev.azure.com/ni/94b22d7b-ad7b-4f5e-88f0-867910f91c94/_workitems/edit/2225400)

**Comment by DavidCurtiss** [comment]
For the 5670, we do not support enabling Direct Download. I can see that the documentation for that attribute isn't entirely clear, but that's what it means. Sorry about that.

**Comment by RT-Tap** [comment]
Ok, thank you for your help.  I was confused because the help file lists PXI5670 as a supported device of this attribute.  

So the description states: `Specifies whether the niRFSG_WriteArbWaveform function immediately writes waveforms to the device or copies the waveform to host memory for later download.` and if this attribute is always off for the PXI5670 does that mean that the PXI5670 always `copies the waveform to host memory for later download` or the opposite, it always `immediately writes waveforms to the device`? 

I am looking through the help file located under ` C:\Program Files (x86)\IVI Foundation\IVI\Drivers\niRFSG\documentation` and also checking [the PXI 5670 device help/overview on ni.com](https://www.ni.com/docs/en-US/bundle/pxi-5670-features/page/overview.html) but I can't seem to find it explicitly stated anywhere.

Again, I appreciate your help looking into this.

**Comment by DavidCurtiss** [comment]
When the help mentions that an attribute is supported, it means you can set/get the attribute without erroring out, but that device may not support all values for that attribute. For the 5670, it means you can set that attribute but to disabled only.

Disabled for that attribute means that the waveform will copy to host memory and will later download it to the device
