### ISSUE TITLE
Distribute debug symbols for official builds

### ISSUE THREAD

**Issue by bkeryan** [ni/grpc-device#813]
Please consider distributing debug symbols for official builds of `ni_grpc_device_server.exe`. This would be helpful for debugging and performance profiling.

One way to do this is to build `BUILD_TYPE=RelWithDebInfo` and generate a separate release artifact for the resulting PDB files.

[AB#2249766](https://dev.azure.com/ni/94b22d7b-ad7b-4f5e-88f0-867910f91c94/_workitems/edit/2249766)

**Comment by maxxboehme** [comment]
Done in #1040
