### ISSUE TITLE
Request for NI-VISA implementation in gRPC

### ISSUE THREAD

**Issue by Livius90** [ni/grpc-device#827]
Is there any roadmap about when will be NI-VISA available in NI gRPC server and client (in Windows 10)? It would be an essential component because in a general measurement system, usually, there are some other 3rd party SCPI, Ivi based devices. They could be used in NI gRPC also.

[AB#2267808](https://dev.azure.com/ni/94b22d7b-ad7b-4f5e-88f0-867910f91c94/_workitems/edit/2267808)

**Comment by DavidCurtiss** [comment]
Answered [here](https://github.com/ni/grpc-device/discussions/728), in the Discussions tab.
> NI-VISA support is on our roadmap currently being targeted for 2nd half of 2023.
