### ISSUE TITLE
NI-FGEN on Linux?

### ISSUE THREAD

**Issue by marcoskirsch** [ni/grpc-device#837]
Per https://github.com/ni/grpc-device/releases/tag/v2.0.0 NI-FGEN on Linux is not supported via gRPC.
NI-FGEN does work on Linux: https://www.ni.com/pdf/manuals/ni-linux-device-drivers-2022-q4.html

Is this a documentation mistake or is there something in NI gRPC Device Server that prevents it from working on Linux while it works on other similar drivers like NI-DCPower?

[AB#2282675](https://dev.azure.com/ni/94b22d7b-ad7b-4f5e-88f0-867910f91c94/_workitems/edit/2282675)

**Comment by reckenro** [comment]
Corrected [Release Notes for 2.0](https://github.com/ni/grpc-device/releases/tag/v2.0.0) and main branch's [Supported NI Drivers ](https://github.com/ni/grpc-device#supported-ni-drivers) section of the README to reflect that FGEN is supported on Linux.
