### ISSUE TITLE
does the function `adjustSampleClockRelativeDelay` delay external clock

### ISSUE THREAD

**Issue by Achuan-2** [ni/grpc-device#874]
[AB#2323114](https://dev.azure.com/ni/94b22d7b-ad7b-4f5e-88f0-867910f91c94/_workitems/edit/2323114)

**Comment by shastriUF** [comment]
@Achuan-2 please ask general questions in the Discussions tab at https://github.com/ni/grpc-device/discussions - this way your question will be visible to others in the community who might also be able to help. We prefer to use GitHub Issues for tracking bugs or requests for changes in the code or related documentation.

**Comment by shastriUF** [comment]
Since this has been open for a while, I'm not asking to close this and re-post in the discussion forum. Keeping this issue open until we can answer this, for this instance

**Comment by Achuan-2** [comment]
ok
