### ISSUE TITLE
FetchArrayMeasurementRequest does not accept meas_wfm_size parameter

### ISSUE THREAD

**Issue by ni-jfitzger** [ni/grpc-device#914]
FetchArrayMeasurementRequest does not accept the meas_wfm_size parameter [defined in the API](https://www.ni.com/docs/en-US/bundle/ni-scope-c-api-ref/page/scopefunc/cviniscope_fetcharraymeasurement.html). Instead, all samples are returned by FetchArrayMeasurementResponse.

[AB#2364316](https://dev.azure.com/ni/94b22d7b-ad7b-4f5e-88f0-867910f91c94/_workitems/edit/2364316)

**Comment by ni-jfitzger** [comment]
This is already fixed. @bkeryan @reckenro if you feel any important details should be added, please do so. This issue was created so that nimi-python could reference it.

**Comment by bkeryan** [comment]
I think the PR description covers the important details:

> Mark the new `meas_wfm_size` as `optional` in the proto request.
> 
> Updates custom service handler to
> 
> 1. If the request's `meas_wfm_size` was set to a non-negative value, use it.
> 2. If it wasn't set or if it was set to a negative number, get the size using `ActualMeasWfmSize`.
This makes it a backwards compatible change and provides the option for a 0-fetch request.
