### ISSUE TITLE
Intermittent Test: NiFgenSessionTest.InitializedSession_CloseSession_ClosesDriverSession

### ISSUE THREAD

**Issue by reckenro** [ni/grpc-device#951]
From this run on a PR: https://github.com/ni/grpc-device/actions/runs/5339863258/jobs/9680561659?pr=950

```
[ RUN      ] NiFgenSessionTest.InitializedSession_CloseSession_ClosesDriverSession
unknown file: Failure
C++ exception with description "MAX:  (Hex 0x80040303) Internal error: The requested object was not found in the configuration database. Please note the steps you performed that led to this error and contact technical support at http://ni.com/support.

Component Name: 
File Name: 
Line Number: 0

Status Code: -2147220733" thrown in the test body.
[  FAILED  ] NiFgenSessionTest.InitializedSession_CloseSession_ClosesDriverSession (415 ms)
```

[AB#2429222](https://dev.azure.com/ni/94b22d7b-ad7b-4f5e-88f0-867910f91c94/_workitems/edit/2429222)

**Comment by bkeryan** [comment]
Good, I was hoping https://github.com/ni/grpc-device/pull/949 would show what's going on with this test.

The NI-FGEN simulation code for this instrument model creates a temporary device entry in the MXS database that is used to track installed devices in MAX. 

A potential workaround is to simulate a different model that uses a different simulation codebase, such as "5423 (2CH)". Example option string: `"Simulate=1, DriverSetup=Model:5423 (2CH); BoardType:PXIe"`

**Comment by reckenro** [comment]
Similar FGEN Failure for a different test from https://github.com/ni/grpc-device/actions/runs/5410336730/jobs/9843887723?pr=957: 

```
[ RUN      ] NiFgenSessionTest.InitializeSessionWithDeviceAndNoSessionName_CreatesDriverSession
unknown file: Failure
C++ exception with description "MAX:  (Hex 0x80040303) Internal error: The requested object was not found in the configuration database. Please note the steps you performed that led to this error and contact technical support at http://ni.com/support.

Component Name: 
File Name: 
Line Number: 0

Status Code: -2147220733" thrown in the test body.
```
