### ISSUE TITLE
Windows system test runner occasionally hits timeout

### ISSUE THREAD

**Issue by reckenro** [ni/grpc-device#952]
Seen in this PR: https://github.com/ni/grpc-device/pull/950

I think we're just starting to hit (since we've been adding driver support / corresponding tests) the arbitrary 27 minute time limit we started with for the Windows system tests: https://github.com/ni/grpc-device/blob/main/.github/workflows/run_win_system_tests.yml#L28

[AB#2429618](https://dev.azure.com/ni/94b22d7b-ad7b-4f5e-88f0-867910f91c94/_workitems/edit/2429618)

**Comment by bkeryan** [comment]
If a GitHub runner instance is reused for multiple jobs, perhaps these timeouts are contributing to other intermittent failures by leaving the runner in a bad state.
