### ISSUE TITLE
Addon metadata isn't merged by the build

### ISSUE THREAD

**Issue by ni-jfitzger** [ni/grpc-device#960]
I tried adding metadata for a new function in `source/codegen/metadata/nidcpower/functions_addon.py` but nothing changed in the generated folder.

I finally tried adding it directly into the `source/codegen/metadata/nidcpower/functions.py` and the function was added to the generated files.

This seems like a clear sign that the addon metadata isn't being merged by the build.

[AB#2456232](https://dev.azure.com/ni/94b22d7b-ad7b-4f5e-88f0-867910f91c94/_workitems/edit/2456232)

**Comment by maxxboehme** [comment]
Closing out. If other products need the merge functionality then the code for those products can be updated during that time.
